version: '3.9'
services:
  db:
    image: postgres:15
    container_name: project_monitor_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_monitor_pro
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
